package com.example.Model;

public class PosSettings {


    int  BRANCH_WISE_PRICE_LEVEL;
    int  PRODUCT_SEARCH_LIMIT;
     boolean  SALES_BLOCK_EXPIRED_ITEMS;
    boolean MRP_SEARCH_WITH_NAME;
    boolean SHOW_VALID_STOCK_ITEMS;
    boolean DISPLAY_STOCK_IN_SALES_RELATED_SEARCHES;
     boolean PRODUCT_WITHMULTI_UNIT;
    boolean SALES_PROMPT_MULTI_UNIT_SELECTION;
    int WEIGHING_SCALE_CODE_CHARACTER_NOS;
    int  WEIGHING_SCALE_CODE_CHARACTER_START_FROM;
    String WEIGHING_SCALE_CODE_INDENTIFICATION_CHARACTER;
    boolean WEIGHING_SCALE_ENABLE;
    int WEIGHING_SCALE_PRICE_QTY_CHARACTER_DECIMALS;
    int WEIGHING_SCALE_PRICE_QTY_CHARACTER_LENGTH;
    int WEIGHING_SCALE_PRICE_QTY_CHARACTER_START_FROM;
    int WEIGHING_SCALE_REMAINING_CHARACTER_FOR;
    int WEIGHING_SCALE_TOTAL_CHARACTER;
    boolean WEIGHING_SCALE_SINGLE_LINE_CODE;

    public int getBRANCH_WISE_PRICE_LEVEL() {
        return BRANCH_WISE_PRICE_LEVEL;
    }

    public void setBRANCH_WISE_PRICE_LEVEL(int BRANCH_WISE_PRICE_LEVEL) {
        this.BRANCH_WISE_PRICE_LEVEL = BRANCH_WISE_PRICE_LEVEL;
    }

    public int getPRODUCT_SEARCH_LIMIT() {
        return PRODUCT_SEARCH_LIMIT;
    }

    public void setPRODUCT_SEARCH_LIMIT(int PRODUCT_SEARCH_LIMIT) {
        this.PRODUCT_SEARCH_LIMIT = PRODUCT_SEARCH_LIMIT;
    }

    public boolean getSALES_BLOCK_EXPIRED_ITEMS() {
        return SALES_BLOCK_EXPIRED_ITEMS;
    }

    public void setSALES_BLOCK_EXPIRED_ITEMS(boolean SALES_BLOCK_EXPIRED_ITEMS) {
        this.SALES_BLOCK_EXPIRED_ITEMS = SALES_BLOCK_EXPIRED_ITEMS;
    }

    public boolean isMRP_SEARCH_WITH_NAME() {
        return MRP_SEARCH_WITH_NAME;
    }

    public void setMRP_SEARCH_WITH_NAME(boolean MRP_SEARCH_WITH_NAME) {
        this.MRP_SEARCH_WITH_NAME = MRP_SEARCH_WITH_NAME;
    }

    public boolean isSHOW_VALID_STOCK_ITEMS() {
        return SHOW_VALID_STOCK_ITEMS;
    }

    public void setSHOW_VALID_STOCK_ITEMS(boolean SHOW_VALID_STOCK_ITEMS) {
        this.SHOW_VALID_STOCK_ITEMS = SHOW_VALID_STOCK_ITEMS;
    }

    public boolean isDISPLAY_STOCK_IN_SALES_RELATED_SEARCHES() {
        return DISPLAY_STOCK_IN_SALES_RELATED_SEARCHES;
    }

    public void setDISPLAY_STOCK_IN_SALES_RELATED_SEARCHES(boolean DISPLAY_STOCK_IN_SALES_RELATED_SEARCHES) {
        this.DISPLAY_STOCK_IN_SALES_RELATED_SEARCHES = DISPLAY_STOCK_IN_SALES_RELATED_SEARCHES;
    }

    public boolean isPRODUCT_WITHMULTI_UNIT() {
        return PRODUCT_WITHMULTI_UNIT;
    }

    public void setPRODUCT_WITHMULTI_UNIT(boolean PRODUCT_WITHMULTI_UNIT) {
        this.PRODUCT_WITHMULTI_UNIT = PRODUCT_WITHMULTI_UNIT;
    }

    public boolean isSALES_PROMPT_MULTI_UNIT_SELECTION() {
        return SALES_PROMPT_MULTI_UNIT_SELECTION;
    }

    public void setSALES_PROMPT_MULTI_UNIT_SELECTION(boolean SALES_PROMPT_MULTI_UNIT_SELECTION) {
        this.SALES_PROMPT_MULTI_UNIT_SELECTION = SALES_PROMPT_MULTI_UNIT_SELECTION;
    }

    public int getWEIGHING_SCALE_CODE_CHARACTER_NOS() {
        return WEIGHING_SCALE_CODE_CHARACTER_NOS;
    }

    public void setWEIGHING_SCALE_CODE_CHARACTER_NOS(int WEIGHING_SCALE_CODE_CHARACTER_NOS) {
        this.WEIGHING_SCALE_CODE_CHARACTER_NOS = WEIGHING_SCALE_CODE_CHARACTER_NOS;
    }

    public int getWEIGHING_SCALE_CODE_CHARACTER_START_FROM() {
        return WEIGHING_SCALE_CODE_CHARACTER_START_FROM;
    }

    public void setWEIGHING_SCALE_CODE_CHARACTER_START_FROM(int WEIGHING_SCALE_CODE_CHARACTER_START_FROM) {
        this.WEIGHING_SCALE_CODE_CHARACTER_START_FROM = WEIGHING_SCALE_CODE_CHARACTER_START_FROM;
    }

    public String getWEIGHING_SCALE_CODE_INDENTIFICATION_CHARACTER() {
        return WEIGHING_SCALE_CODE_INDENTIFICATION_CHARACTER;
    }

    public void setWEIGHING_SCALE_CODE_INDENTIFICATION_CHARACTER(String WEIGHING_SCALE_CODE_INDENTIFICATION_CHARACTER) {
        this.WEIGHING_SCALE_CODE_INDENTIFICATION_CHARACTER = WEIGHING_SCALE_CODE_INDENTIFICATION_CHARACTER;
    }

    public boolean isWEIGHING_SCALE_ENABLE() {
        return WEIGHING_SCALE_ENABLE;
    }

    public void setWEIGHING_SCALE_ENABLE(boolean WEIGHING_SCALE_ENABLE) {
        this.WEIGHING_SCALE_ENABLE = WEIGHING_SCALE_ENABLE;
    }

    public int getWEIGHING_SCALE_PRICE_QTY_CHARACTER_DECIMALS() {
        return WEIGHING_SCALE_PRICE_QTY_CHARACTER_DECIMALS;
    }

    public void setWEIGHING_SCALE_PRICE_QTY_CHARACTER_DECIMALS(int WEIGHING_SCALE_PRICE_QTY_CHARACTER_DECIMALS) {
        this.WEIGHING_SCALE_PRICE_QTY_CHARACTER_DECIMALS = WEIGHING_SCALE_PRICE_QTY_CHARACTER_DECIMALS;
    }

    public int getWEIGHING_SCALE_PRICE_QTY_CHARACTER_LENGTH() {
        return WEIGHING_SCALE_PRICE_QTY_CHARACTER_LENGTH;
    }

    public void setWEIGHING_SCALE_PRICE_QTY_CHARACTER_LENGTH(int WEIGHING_SCALE_PRICE_QTY_CHARACTER_LENGTH) {
        this.WEIGHING_SCALE_PRICE_QTY_CHARACTER_LENGTH = WEIGHING_SCALE_PRICE_QTY_CHARACTER_LENGTH;
    }

    public int getWEIGHING_SCALE_PRICE_QTY_CHARACTER_START_FROM() {
        return WEIGHING_SCALE_PRICE_QTY_CHARACTER_START_FROM;
    }

    public void setWEIGHING_SCALE_PRICE_QTY_CHARACTER_START_FROM(int WEIGHING_SCALE_PRICE_QTY_CHARACTER_START_FROM) {
        this.WEIGHING_SCALE_PRICE_QTY_CHARACTER_START_FROM = WEIGHING_SCALE_PRICE_QTY_CHARACTER_START_FROM;
    }

    public int getWEIGHING_SCALE_REMAINING_CHARACTER_FOR() {
        return WEIGHING_SCALE_REMAINING_CHARACTER_FOR;
    }

    public void setWEIGHING_SCALE_REMAINING_CHARACTER_FOR(int WEIGHING_SCALE_REMAINING_CHARACTER_FOR) {
        this.WEIGHING_SCALE_REMAINING_CHARACTER_FOR = WEIGHING_SCALE_REMAINING_CHARACTER_FOR;
    }

    public int getWEIGHING_SCALE_TOTAL_CHARACTER() {
        return WEIGHING_SCALE_TOTAL_CHARACTER;
    }

    public void setWEIGHING_SCALE_TOTAL_CHARACTER(int WEIGHING_SCALE_TOTAL_CHARACTER) {
        this.WEIGHING_SCALE_TOTAL_CHARACTER = WEIGHING_SCALE_TOTAL_CHARACTER;
    }

    public boolean isWEIGHING_SCALE_SINGLE_LINE_CODE() {
        return WEIGHING_SCALE_SINGLE_LINE_CODE;
    }

    public void setWEIGHING_SCALE_SINGLE_LINE_CODE(boolean WEIGHING_SCALE_SINGLE_LINE_CODE) {
        this.WEIGHING_SCALE_SINGLE_LINE_CODE = WEIGHING_SCALE_SINGLE_LINE_CODE;
    }
}
